# Movie Recommendation System

### Loading Libraries & Dataset

In [2]:
import pandas as pd

In [3]:
data = pd.read_csv('assets/movies.csv')

In [4]:
data.info()
data.columns

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 63249 entries, 0 to 63248
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     63249 non-null  object
 1   title                  63249 non-null  object
 2   year                   63249 non-null  int64
 3   duration               61174 non-null  object
 4   MPA                    41227 non-null  object
 5   rating                 59181 non-null  float64
 6   votes                  59181 non-null  object
 7   meta_score             15533 non-null  float64
 8   description            60889 non-null  object
 9   Movie_Link             63249 non-null  object
 10  writers                62980 non-null  object
 11  directors              63198 non-null  object
 12  stars                  62905 non-null  object
 13  budget                 15359 non-null  object
 14  opening_weekend_gross  16837 non-null  object
 15  gross_worldwide        20722 non-null  object
 16  gross_us_canada        19544 non-null  object
 17  release_date           54849 non-null  float64
 18  countries_origin       63150 non-null  object
 19  filming_locations      46395 non-null  object
 20  production_companies   61276 non-null  object
 21  awards_content         27068 non-null  object
 22  genres                 62462 non-null  object
 23  languages              62919 non-null  object
dtypes: float64(3), int64(1), object(20)
memory usage: 11.6+ MB

Index(['id', 'title', 'year', 'duration', 'MPA', 'rating', 'votes',
       'meta_score', 'description', 'Movie_Link', 'writers', 'directors',
       'stars', 'budget', 'opening_weekend_gross', 'gross_worldwide',
       'gross_us_canada', 'release_date', 'countries_origin',
       'filming_locations', 'production_companies', 'awards_content', 'genres',
       'languages'],
      dtype='object')

In [5]:
data.head()

,id,title,year,duration,MPA,rating,votes,meta_score,description,Movie_Link,...,opening_weekend_gross,gross_worldwide,gross_us_canada,release_date,countries_origin,filming_locations,production_companies,awards_content,genres,languages
0,tt0073195,Jaws,1975,2h 4m,PG,8.1,690K,87.0,When a massive killer shark unleashes chaos on...,https://www.imdb.com/title/tt0073195,...,"$7,061,513","$477,916,625","$267,263,625",1975.0,['United States'],"[""Water Street, Edgartown, Martha's Vineyard, ...","['Zanuck/Brown Productions', 'Universal Pictur...","Won 3 Oscars, 16 wins & 20 nominations total","['Monster Horror', 'Sea Adventure', 'Survival'...",['English']
1,tt0073629,The Rocky Horror Picture Show,1975,1h 40m,R,7.4,174K,65.0,A newly-engaged couple have a breakdown in an ...,https://www.imdb.com/title/tt0073629,...,NaN,"$115,827,018","$112,892,319",1975.0,"['United Kingdom', 'United States']","[""Oakley Court, Windsor Road, Oakley Green, Wi...","['Twentieth Century Fox', 'Michael White Produ...","Awards, 3 wins & 4 nominations total","['B-Horror', 'Dark Comedy', 'Parody', 'Raunchy...",['English']
2,tt0073486,One Flew Over the Cuckoo's Nest,1975,2h 13m,R,8.7,1.1M,84.0,"In the Fall of 1963, a Korean War veteran and ...",https://www.imdb.com/title/tt0073486,...,NaN,"$109,115,366","$108,981,275",1975.0,['United States'],['Oregon State Mental Hospital - 2600 Center S...,"['Fantasy Films', 'N.V. Zvaluw']","Won 5 Oscars, 38 wins & 15 nominations total","['Medical Drama', 'Psychological Drama', 'Drama']",['English']
3,tt0072890,Dog Day Afternoon,1975,2h 5m,R,8.0,281K,86.0,Three amateur robbers plan to hold up a Brookl...,https://www.imdb.com/title/tt0072890,...,NaN,"$50,004,527","$50,000,000",1975.0,['United States'],"['285 Prospect Park West, Brooklyn, New York C...","['Warner Bros.', 'Artists Entertainment Complex']","Won 1 Oscar, 14 wins & 20 nominations total","['Dark Comedy', 'Heist', 'True Crime', 'Biogra...",['English']
4,tt0073692,Shampoo,1975,1h 50m,R,6.4,15K,65.0,"On Election Day, 1968, irresponsible hairdress...",https://www.imdb.com/title/tt0073692,...,NaN,"$49,407,734","$49,407,734",1975.0,['United States'],"[""2270 Bowmont Drive, Beverly Hills, Californi...","['Persky-Bright / Vista', 'Columbia Pictures',...","Won 1 Oscar, 3 wins & 11 nominations total","['Satire', 'Comedy', 'Drama']",['English']

### Trimming down to important columns

In [6]:
data = data[
    [
        'id', 
        'title',
        'rating',
        'description',
        'writers', 
        'directors', 
        'stars', 
        'genres' 
    ]
]
data.head()

,id,title,rating,description,writers,directors,stars,genres
0,tt0073195,Jaws,8.1,When a massive killer shark unleashes chaos on...,"['Peter Benchley', 'Carl Gottlieb']",['Steven Spielberg'],"['Roy Scheider', 'Robert Shaw', 'Richard Dreyf...","['Monster Horror', 'Sea Adventure', 'Survival'..."
1,tt0073629,The Rocky Horror Picture Show,7.4,A newly-engaged couple have a breakdown in an ...,"[""Richard O'Brien"", 'Jim Sharman']",['Jim Sharman'],"['Tim Curry', 'Susan Sarandon', 'Barry Bostwic...","['B-Horror', 'Dark Comedy', 'Parody', 'Raunchy..."
2,tt0073486,One Flew Over the Cuckoo's Nest,8.7,"In the Fall of 1963, a Korean War veteran and ...","['Lawrence Hauben', 'Bo Goldman', 'Ken Kesey']",['Milos Forman'],"['Jack Nicholson', 'Louise Fletcher', 'Michael...","['Medical Drama', 'Psychological Drama', 'Drama']"
3,tt0072890,Dog Day Afternoon,8.0,Three amateur robbers plan to hold up a Brookl...,"['Frank Pierson', 'P.F. Kluge', 'Thomas Moore']",['Sidney Lumet'],"['Al Pacino', 'John Cazale', 'Penelope Allen',...","['Dark Comedy', 'Heist', 'True Crime', 'Biogra..."
4,tt0073692,Shampoo,6.4,"On Election Day, 1968, irresponsible hairdress...","['Robert Towne', 'Warren Beatty']",['Hal Ashby'],"['Warren Beatty', 'Julie Christie', 'Goldie Ha...","['Satire', 'Comedy', 'Drama']"

### Dropping null values

In [7]:
data = data[data['description'].notna()]
data = data[data['writers'].notna()]
data = data[data['stars'].notna()]
data = data[data['genres'].notna()]
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 60277 entries, 0 to 63248
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           60277 non-null  object
 1   title        60277 non-null  object
 2   rating       57423 non-null  float64
 3   description  60277 non-null  object
 4   writers      60277 non-null  object
 5   directors    60277 non-null  object
 6   stars        60277 non-null  object
 7   genres       60277 non-null  object
dtypes: float64(1), object(7)
memory usage: 4.1+ MB

In [8]:
data["rating"] = data["rating"].fillna(0)
data.head()

,id,title,rating,description,writers,directors,stars,genres
0,tt0073195,Jaws,8.1,When a massive killer shark unleashes chaos on...,"['Peter Benchley', 'Carl Gottlieb']",['Steven Spielberg'],"['Roy Scheider', 'Robert Shaw', 'Richard Dreyf...","['Monster Horror', 'Sea Adventure', 'Survival'..."
1,tt0073629,The Rocky Horror Picture Show,7.4,A newly-engaged couple have a breakdown in an ...,"[""Richard O'Brien"", 'Jim Sharman']",['Jim Sharman'],"['Tim Curry', 'Susan Sarandon', 'Barry Bostwic...","['B-Horror', 'Dark Comedy', 'Parody', 'Raunchy..."
2,tt0073486,One Flew Over the Cuckoo's Nest,8.7,"In the Fall of 1963, a Korean War veteran and ...","['Lawrence Hauben', 'Bo Goldman', 'Ken Kesey']",['Milos Forman'],"['Jack Nicholson', 'Louise Fletcher', 'Michael...","['Medical Drama', 'Psychological Drama', 'Drama']"
3,tt0072890,Dog Day Afternoon,8.0,Three amateur robbers plan to hold up a Brookl...,"['Frank Pierson', 'P.F. Kluge', 'Thomas Moore']",['Sidney Lumet'],"['Al Pacino', 'John Cazale', 'Penelope Allen',...","['Dark Comedy', 'Heist', 'True Crime', 'Biogra..."
4,tt0073692,Shampoo,6.4,"On Election Day, 1968, irresponsible hairdress...","['Robert Towne', 'Warren Beatty']",['Hal Ashby'],"['Warren Beatty', 'Julie Christie', 'Goldie Ha...","['Satire', 'Comedy', 'Drama']"

### Tag prepration

In [9]:
def to_list(x):
    import ast
    return ast.literal_eval(x)[:7]

def description_to_list(x):
    return [i for i in x.split(' ')]

def title_to_list(x):
    return [i for i in x.split(' ')]

def limiter(x):
    return x[:7]

In [10]:
# List Conversion
data['writers'] = data['writers'].apply(to_list)
data['directors'] = data['directors'].apply(to_list)
data['stars'] = data['stars'].apply(to_list)
data['genres'] = data['genres'].apply(to_list)

data['description'] = data['description'].apply(description_to_list)
data['title_for_tag'] = data['title'].apply(title_to_list)

data.head()

,id,title,rating,description,writers,directors,stars,genres,title_for_tag
0,tt0073195,Jaws,8.1,"[When, a, massive, killer, shark, unleashes, c...","[Peter Benchley, Carl Gottlieb]",[Steven Spielberg],"[Roy Scheider, Robert Shaw, Richard Dreyfuss, ...","[Monster Horror, Sea Adventure, Survival, Adve...",[Jaws]
1,tt0073629,The Rocky Horror Picture Show,7.4,"[A, newly-engaged, couple, have, a, breakdown,...","[Richard O'Brien, Jim Sharman]",[Jim Sharman],"[Tim Curry, Susan Sarandon, Barry Bostwick, Ri...","[B-Horror, Dark Comedy, Parody, Raunchy Comedy...","[The, Rocky, Horror, Picture, Show]"
2,tt0073486,One Flew Over the Cuckoo's Nest,8.7,"[In, the, Fall, of, 1963,, a, Korean, War, vet...","[Lawrence Hauben, Bo Goldman, Ken Kesey]",[Milos Forman],"[Jack Nicholson, Louise Fletcher, Michael Berr...","[Medical Drama, Psychological Drama, Drama]","[One, Flew, Over, the, Cuckoo's, Nest]"
3,tt0072890,Dog Day Afternoon,8.0,"[Three, amateur, robbers, plan, to, hold, up, ...","[Frank Pierson, P.F. Kluge, Thomas Moore]",[Sidney Lumet],"[Al Pacino, John Cazale, Penelope Allen, Sully...","[Dark Comedy, Heist, True Crime, Biography, Cr...","[Dog, Day, Afternoon]"
4,tt0073692,Shampoo,6.4,"[On, Election, Day,, 1968,, irresponsible, hai...","[Robert Towne, Warren Beatty]",[Hal Ashby],"[Warren Beatty, Julie Christie, Goldie Hawn, L...","[Satire, Comedy, Drama]",[Shampoo]

In [11]:
data['tag'] = data['title_for_tag'] + data['description'] + data['writers'] + data['directors'] + data['stars'] + data['genres']
data["tag"] = data["tag"].apply(lambda x: " ".join(x).lower())
data = data[["id", "title", "rating", "tag"]]
data.head()

,id,title,rating,tag
0,tt0073195,Jaws,8.1,jaws when a massive killer shark unleashes cha...
1,tt0073629,The Rocky Horror Picture Show,7.4,the rocky horror picture show a newly-engaged ...
2,tt0073486,One Flew Over the Cuckoo's Nest,8.7,one flew over the cuckoo's nest in the fall of...
3,tt0072890,Dog Day Afternoon,8.0,dog day afternoon three amateur robbers plan t...
4,tt0073692,Shampoo,6.4,"shampoo on election day, 1968, irresponsible h..."

### Stemming the tag

In [12]:
from nltk.stem.porter import PorterStemmer

ps = PorterStemmer()
def stem(text):
    y = [ps.stem(i) for i in text.split()]
    return " ".join(y)

In [13]:
data['tag'] = data['tag'].apply(stem)

In [14]:
data.head()

,id,title,rating,tag
0,tt0073195,Jaws,8.1,jaw when a massiv killer shark unleash chao on...
1,tt0073629,The Rocky Horror Picture Show,7.4,the rocki horror pictur show a newly-engag cou...
2,tt0073486,One Flew Over the Cuckoo's Nest,8.7,one flew over the cuckoo' nest in the fall of ...
3,tt0072890,Dog Day Afternoon,8.0,dog day afternoon three amateur robber plan to...
4,tt0073692,Shampoo,6.4,"shampoo on elect day, 1968, irrespons hairdres..."

### Vectorizing with TF-IDF

In [15]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer(max_features=15000, stop_words='english', ngram_range=(1,2))
vector = tfidf.fit_transform(data['tag'])

### Setting up Near Neighbour

In [16]:
from sklearn.neighbors import NearestNeighbors
model = NearestNeighbors(n_neighbors=6, metric='cosine', algorithm='brute')
model.fit(vector)

NearestNeighbors(algorithm='brute', metric='cosine', n_neighbors=6)

In [23]:
position = data[data["title"] == "Jurassic World"]

if position.empty:
    print("Position not found")
else:
    iloc_index = data.index.get_loc(position.index[0])
    iloc_index

In [25]:
_, indices = model.kneighbors(vector[iloc_index], n_neighbors=6)
for i in indices[0][1:]:
    print(data.iloc[i]["title"])

Jurassic World: Fallen Kingdom
Jurassic World: Dominion
The Lost World: Jurassic Park
The Last Dinosaur
Jurassic Park